steps:
  - command: "sleep 10 && echo Shared"
    label: "Build Shared Libraries"

  - command: "sleep 30 && echo Web"
    label: "Build Web"

  - command: "sleep 5 && echo API"
    label: "Build API"

  - "wait"

  - command: "echo Deploy"
    label: "Deploy"
